export const AWS_CONFIG = {
  DEFAULT_REGION: 'ap-south-1',
  DEFAULT_BUCKET_NAME: 's3-document-processor',
  PRESIGNED_URL_EXPIRY_SECONDS: 900,
  DEFAULT_MAX_RECEIVE_COUNT: 1,
  DEFAULT_SQS_WAIT_TIME_SECONDS: 20,
  DEFAULT_SQS_POLLING_WAIT_TIME_MS: 1000,
};
