export const CHUNKING_CONFIG = {
  DEFAULT_CHUNK_SIZE: 2200,
  DEFAULT_OVERLAP: 350,
  DEFAULT_MAX_CHUNKS: 120,
  MAX_TOTAL_DOCUMENT_CHUNKS: 120,
  PARAGRAPH_LOOKBACK: 250,
  PARAGRAPH_LOOKAHEAD: 150,
  SENTENCE_LOOKBACK: 150,
  SENTENCE_LOOKAHEAD: 80,
  EVENT_LOOP_YIELD_INTERVAL: 50,
};
