export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  LOGIN_ERROR: 'LOGIN_ERROR',
  PROFILE_ERROR: 'PROFILE_ERROR',

  // Validation
  VALIDATION_ERROR: 'Validation Error',
  BAD_REQUEST: 'BAD_REQUEST',

  // File Upload
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  TOO_MANY_FILES: 'TOO_MANY_FILES',
  FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // Query
  QUERY_ERROR: 'QUERY_ERROR',
};
