import { ALLOWED_MIME_TYPES, ALLOWED_FILE_EXTENSIONS, UPLOAD_LIMITS, TEXT_FILE_EXTENSIONS, TEXT_MIME_TYPES, PREVIEW_LIMITS } from './fileTypes.js';
import { QUEUES } from './queues.js';
import { SESSION_STATUS, DOCUMENT_STATUS, MESSAGE_SENDER } from './status.js';
import { CHUNKING_CONFIG } from './chunking.js';
import { RAG_CONFIG } from './rag.js';
import { GEMINI_CONFIG, SYSTEM_INSTRUCTIONS } from './gemini.js';
import { AWS_CONFIG } from './aws.js';
import { AUTH_CONFIG } from './auth.js';
import { HTTP_STATUS } from './http.js';
import { ERROR_CODES } from './errors.js';
import { PAGINATION } from './pagination.js';
import { SSE_CONFIG } from './sse.js';
import { AI_VENDORS, OPENAI_CONFIG, AI_ORCHESTRATION } from './ai.js';

export const constant = {
  ENVS: {
    LOCAL: 'local',
    DEV: 'development',
    PROD: 'production',
    TEST: 'test',
  },
  ALLOWED_MIME_TYPES,
  ALLOWED_FILE_EXTENSIONS,
  UPLOAD_LIMITS,
  TEXT_FILE_EXTENSIONS,
  TEXT_MIME_TYPES,
  PREVIEW_LIMITS,
  QUEUES,
  SESSION_STATUS,
  DOCUMENT_STATUS,
  MESSAGE_SENDER,
  CHUNKING_CONFIG,
  RAG_CONFIG,
  GEMINI_CONFIG,
  SYSTEM_INSTRUCTIONS,
  AWS_CONFIG,
  AUTH_CONFIG,
  HTTP_STATUS,
  ERROR_CODES,
  PAGINATION,
  SSE_CONFIG,
  AI_VENDORS,
  OPENAI_CONFIG,
  AI_ORCHESTRATION,
};

export {
  ALLOWED_MIME_TYPES,
  ALLOWED_FILE_EXTENSIONS,
  UPLOAD_LIMITS,
  TEXT_FILE_EXTENSIONS,
  TEXT_MIME_TYPES,
  PREVIEW_LIMITS,
  QUEUES,
  SESSION_STATUS,
  DOCUMENT_STATUS,
  MESSAGE_SENDER,
  CHUNKING_CONFIG,
  RAG_CONFIG,
  GEMINI_CONFIG,
  SYSTEM_INSTRUCTIONS,
  AWS_CONFIG,
  AUTH_CONFIG,
  HTTP_STATUS,
  ERROR_CODES,
  PAGINATION,
  SSE_CONFIG,
  AI_VENDORS,
  OPENAI_CONFIG,
  AI_ORCHESTRATION,
};
