export const RAG_CONFIG = {
  DEFAULT_TOP_K: 8,
  MIN_SIMILARITY_THRESHOLD: 0.45,
  RELATIVE_SCORE_THRESHOLD: 0.70,
  KEYWORD_MATCH_FALLBACK_SCORE: 0.8,
  DEFAULT_FALLBACK_SCORE: 0.1,
  DEFAULT_DOCUMENT_NAME: 'Document',
  SNIPPET_MAX_LENGTH: 300,
  FALLBACK_TOP_K: 3,
};
